### ISSUE TITLE
Locally installed + built ink-redux can't render connected components.

### ISSUE THREAD

**Issue by xdave** [vadimdemedes/ink-redux#2]
Steps to reproduce:

```
# mkdir test
# cd test
# yarn init --yes
# yarn add redux ink vadimdemedes/ink-redux
# (or `yarn add file:../somepath/ink-redux` for example)
# cd node_modules/ink-redux && yarn && cd ../..
```
Paste the following code into a file:
### index.js
```js
const { h, mount } = require('ink');
const { Provider, connect } = require('ink-redux');
const { createStore } = require('redux');

const store = createStore((state, action) => {
    return state;
}, {
    message: 'Hello'
});

const mapStateToProps = state => ({
    message: state.message
});

const connector = connect(mapStateToProps);

const View = connector(({ message }) => (
    h('div', null, message)
));

mount(h(Provider, { store }, h(View, null)), process.stdout);
```
And run it.  It should produce the following error:
```
/home/dave/Projects/ink-redux-test/node_modules/ink/lib/render-to-string.js:23
        if (instance.instance instanceof StringComponent) {
                    ^

TypeError: Cannot read property 'instance' of undefined
    at renderToString (/home/dave/Projects/ink-redux-test/node_modules/ink/lib/render-to-string.js:23:14)
    at Array.map (native)
    at renderToString (/home/dave/Projects/ink-redux-test/node_modules/ink/lib/render-to-string.js:17:5)
    at renderToString (/home/dave/Projects/ink-redux-test/node_modules/ink/lib/render-to-string.js:28:9)
    at Array.map (native)
    at renderToString (/home/dave/Projects/ink-redux-test/node_modules/ink/lib/render-to-string.js:17:5)
    at renderToString (/home/dave/Projects/ink-redux-test/node_modules/ink/lib/render-to-string.js:28:9)
    at exports.mount (/home/dave/Projects/ink-redux-test/node_modules/ink/index.js:66:6)
    at Object.<anonymous> (/home/dave/Projects/ink-redux-test/index.js:21:1)
    at Module._compile (module.js:569:30)
```
If I remove the locally installed version and install the one from npm, everything works fine, for example:
```
# yarn remove ink-redux && yarn add ink-redux
# node index
```
You get the following output:
```
Hello
```

**Comment by vadimdemedes** [comment]
`yarn add vadimdemedes/ink` installs Ink (and any other package) directly from GitHub repository, which won't work, because `dist` folder contains the code and it's missing in the git repository. So that's not a bug, but an expected behavior. As you can see, there's `src` folder, which contains the sources with JSX inside and `dist` folder, which contains transpiled code.

**Comment by xdave** [comment]
If you read what I said in my issue report, I'm manually compiling the code after it pulls it in.  So this error is indeed thrown with the dist compiled code.

**Comment by vadimdemedes** [comment]
Didn't find that info in your original post, that you were compiling the code. As you said yourself, the version from npm works, so it must be something local to you.

**Comment by xdave** [comment]
`# cd node_modules/ink-redux && yarn && cd ../..`

This is the equivalent of `npm install`, which builds the package.

**Comment by vadimdemedes** [comment]
In that case, I'd console.log all the components you use in your script and see which one of them is `undefined`.

**Comment by xdave** [comment]
Between trying the locally vs. npm installed ink-redux, I've tried:
- Comparing the compiled sources of both ink-redux and my test project (using diff)
- console.log()'ing the components to see where there may be something undefined in props.children[]

I haven't noticed anything yet.

I did notice that you have a `yarn.lock` file which has been .gitignore'd in the package.  I wonder if you have some versions of deps that are getting installed which affect the build that goes to npm in ways that are different than anyone else.  This is entirely possible.  Here's my yarn lock file (against the master branch of ink-redux) for comparison:

https://gist.github.com/xdave/3242beccac4bc7f2a6c829edbfc93fc1

**Comment by vadimdemedes** [comment]
> I did notice that you have a `yarn.lock` file which has been .gitignore'd in the package.

Where? I don't even use Yarn.

Could you also update to the latest Ink and see if it resolves the issue?

**Comment by xdave** [comment]
Here's the contents of `.gitignore` in ink-redux:

```
node_modules
yarn.lock
dist
```

I'm using ink 0.1.2.

**Comment by sindresorhus** [comment]
@xdave We ignore `yarn.lock` so Yarn users won't commit lock files in PRs.

**Comment by vadimdemedes** [comment]
Oh, when you said "that you have a yarn.lock file", I thought I had it in the repository somehow.

**Comment by xdave** [comment]
I also tried npm.  Version 4.x and also 5.2.0

**Comment by vadimdemedes** [comment]
OH. I got it.

Go to `ink-redux` folder and:

```
$ rm -rf node_modules
$ npm install --production
```

Try again :)

**Comment by xdave** [comment]
That doesn't seem to work, `--production` doesn't install anything, because there are no `dependencies` in the `ink-redux` package, only `devDependencies`.  My test project then complains that `redux` and `ink` are missing, even though they're installed.
