### ISSUE TITLE
This no longer works with your newest version of ink

### ISSUE THREAD

**Issue by Bram-Zijp** [vadimdemedes/ink-redux#4]
I believe you no longer export `h, Component` from your ink package.

**Comment by vadimdemedes** [comment]
There shouldn't be a need to use this package with Ink 2 anymore. You can use Redux directly.

**Comment by pranshuchittora** [comment]
Can't use react-redux as well. Any workaround for using Provider

> There shouldn't be a need to use this package with Ink 2 anymore. You can use Redux directly.
